### ISSUE TITLE
Overflow issue

### ISSUE THREAD

**Issue by ruzzle** [BinaryDefense/IcedDecrypt#2]
I tried running the tool on a license.dat in a IR case, but ran into the following issue:

[+] decryption key for dat file: 00000000000000000000000000000000
[+] Size of data: 341098
[+] Size: 341078
Traceback (most recent call last):
  File "IcedDecrypt.py", line 434, in <module>
    icedDec.main()
  File "IcedDecrypt.py", line 78, in main
    outdata = self.decrypt(data, size=len(data) - 20, key=key)
  File "IcedDecrypt.py", line 239, in decrypt
    key = self.fixKey(key, x * 4, y * 4)
  File "IcedDecrypt.py", line 217, in fixKey
    tempValY = tempVal.to_bytes(4, byteorder="little")
OverflowError: int too big to convert

Any thoughts?

**Comment by ruzzle** [comment]
Posted too quickly. Was an export issue of this file. It worked now!
